// users

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

// Tickets
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKET_SUCCESS = 'GET_TICKET_SUCCESS';

// accounts

export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';

// comments

export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';

// comments

export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const ADD_BLOG_SUCCESS = 'ADD_BLOG_SUCCESS';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';
