# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d770173782a1552b4333b280be7148eee3f1231337e194dce759ed01a4aaaa28af1326ad91a488e02f7ff64aad75f13fdaead5105fbedf3e329b57c01681e7f7

test:
  secret_key_base: ba759a14fed2159c7e2d4d62482b7c30506fbf0fd998a130d5ec4ce8a6bf5b1b0b6e21bc91e0656d0f290c6ab6fbdfbe9f295c99b342366c2bf6691201d46423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
